const products = {
  dth: { family: "DTH SERIES", name: "恒温恒湿试验箱", image: "assets/products/machine-02-dson-subtle.png", intro: "用于电子、汽车零部件、新能源、材料与科研样品的高低温及交变湿热试验。", specs: [["标准容积", "165L、225L、408L、800L、1000L"], ["温度范围", "典型 -70℃ 至 +150℃，以选型为准"], ["湿度范围", "10% 至 98%RH，依温度条件确认"], ["控制方式", "触控式程序控制"]], features: ["多种容积与温度等级可选", "温湿度程序可按试验条件设定", "支持按项目需求配置接口与视窗"] },
  multilayer: { family: "JHHS SERIES", name: "多层式恒温恒湿试验箱", image: "assets/products/catalog/multilayer-chamber-dson.png", intro: "上下双层独立测试空间，可在有限场地内提高样品并行测试效率。", specs: [["参考型号", "JHHS-415T"], ["结构", "双层独立试验空间"], ["试验类型", "恒温、恒湿及交变湿热"], ["配置方式", "容积与温湿度条件按项目确认"]], features: ["独立空间减少测试排程等待", "适合多批次样品并行验证", "可依样品尺寸与负载配置"] },
  rapid: { family: "RAPID CHANGE", name: "快速温度变化试验箱", image: "assets/products/machine-01-dson-subtle.png", intro: "为快速温度变化与环境应力筛选设计，适用于需要控制升降温速率的可靠性试验。", specs: [["温度范围", "-70℃ 至 +150℃"], ["升降温性能", "5℃ 至 25℃/min，依型号与负载确认"], ["湿度选配", "20% 至 98%RH"], ["标准台体", "800L 参考规格，可依需求定制"]], features: ["适配快速温变与应力筛选", "支持线性或非线性温变方案", "可加装干空气吹扫装置"] },
  drug: { family: "PJHH SERIES", name: "药品稳定性试验箱", image: "assets/products/catalog/drug-stability-chamber-dson.png", intro: "用于药品长期、加速与稳定性环境试验，支持温湿度程序控制与数据记录。", specs: [["参考型号", "PJHH-B、PJHH-D"], ["试验类型", "长期、加速及稳定性试验"], ["控制", "温湿度程序控制"], ["记录", "可按项目配置数据记录功能"]], features: ["适合稳定性验证环境", "支持长期运行与程序设定", "配置以药品试验要求确认"] },
  walkin: { family: "WALK-IN SERIES", name: "步入式恒温恒湿试验室", image: "assets/products/machine-04-dson-subtle.png", intro: "面向大型工件、整机与批量样品的环境模拟与可靠性试验，可按现场空间规划。", specs: [["结构", "步入式试验室"], ["适用对象", "大型工件、整机及批量样品"], ["环境条件", "温湿度范围按项目确认"], ["尺寸", "可依据样品、场地与负载定制"]], features: ["适合大尺寸或多件样品", "可结合现场供电与冷却条件设计", "便于规划测试工位与进出料方式"] },
  photovoltaic: { family: "JHWA SERIES", name: "光伏组件专用试验箱", image: "assets/products/catalog/photovoltaic-chamber-dson.png", intro: "面向大型光伏组件的湿热、湿冻与温度循环试验，可依据组件数量与尺寸配置空间。", specs: [["参考型号", "JHWA-R12T-8P、JHWA-412T-8P 等"], ["适用试验", "湿热、湿冻与温度循环"], ["空间", "按组件尺寸与数量配置"], ["配置", "按负载与现场条件确认"]], features: ["适合光伏组件环境可靠性验证", "支持大型样品空间规划", "可依试验标准确认配置"] },
  twoZoneShock: { family: "DLCT SERIES", name: "两箱式冷热冲击试验箱", image: "assets/products/machine-03-dson-subtle.png", intro: "采用两箱移动式结构，通过高低温区切换完成冷热冲击试验，覆盖多种内箱尺寸与低温等级。", specs: [["参考型号", "DLCT-B2 至 DLCT-D4"], ["内箱尺寸", "40×40×30、50×50×30、60×60×30cm"], ["高温冲击", "+60℃ 至 +150℃"], ["低温冲击", "-10℃ 至 -65℃，依型号确认"]], features: ["两箱式移动结构", "适合冷热冲击循环试验", "型号可依样品尺寸与低温等级选择"] },
  threeZoneShock: { family: "JHS SERIES", name: "三箱式冷热冲击试验箱", image: "assets/products/catalog/three-zone-shock-dson.png", intro: "高温区、低温区与测试区三箱结构，适合自动冷热冲击循环与标准化试验。", specs: [["结构", "高温区、低温区与测试区"], ["适用试验", "冷热冲击与温度循环"], ["切换", "气门快速切换"], ["配置", "温度等级与测试区尺寸按项目确认"]], features: ["测试样品可留在测试区", "支持自动循环试验", "适合标准化冲击测试流程"] },
  equalShock: { family: "JHSR SERIES", name: "等均温冷热冲击试验箱", image: "assets/products/catalog/equal-temperature-shock-dson.png", intro: "通过可控温变速率完成快速循环，适用于需要兼顾均温与冷热冲击条件的测试场景。", specs: [["系列", "JHSR"], ["试验类型", "等均温快速循环与冷热冲击"], ["控制", "温变速率按试验条件设定"], ["配置", "温度范围与负载按项目确认"]], features: ["兼顾均温与温变需求", "适合可靠性快速循环验证", "支持依标准与样品条件选型"] },
  vibration: { family: "JHVE SERIES", name: "温湿度振动三综合试验箱", image: "assets/products/catalog/vibration-combined-chamber-dson.png", intro: "将温度、湿度与振动条件组合，用于多应力综合环境可靠性验证。", specs: [["系列", "JHVE"], ["组合条件", "温度、湿度与振动"], ["适用对象", "电子产品、部件与模组"], ["配置", "振动接口与环境条件按项目确认"]], features: ["多应力同步或组合试验", "适合综合环境可靠性验证", "可配合振动台进行系统规划"] },
  ess: { family: "JHESS SERIES", name: "四合一 ESS 应力筛选试验箱", image: "assets/products/catalog/ess-chamber-clean.png", intro: "整合快速温变、凝露、湿度循环与振动应用，用于环境应力筛选。", specs: [["系列", "JHESS"], ["组合能力", "快速温变、凝露、湿度循环与振动"], ["应用", "环境应力筛选"], ["配置", "试验程序与接口按项目确认"]], features: ["覆盖多种应力筛选条件", "适合提升可靠性筛选效率", "配置依样品与测试计划确认"] },
  saltSpray: { family: "JHL SERIES", name: "盐水喷雾试验机", image: "assets/products/catalog/salt-spray-chamber-dson.png", intro: "用于金属、涂层及零部件耐腐蚀测试，覆盖 NSS、ACSS 与 CASS 条件。", specs: [["参考型号", "JHL-60-SS 至 JHL-200-NS"], ["容量范围", "108L 至 1440L"], ["试验条件", "NSS、ACSS、CASS"], ["适用对象", "金属、涂层及零部件"]], features: ["覆盖多种试验空间", "适合耐腐蚀可靠性评估", "具体条件依试验标准确认"] },
  rain: { family: "JHR SERIES", name: "耐雨淋试验箱", image: "assets/products/catalog/rain-test-chamber-dson.png", intro: "用于外壳防水和汽车零部件淋雨试验，覆盖滴水、摆管与喷嘴条件。", specs: [["系列", "JHR"], ["防水条件", "IPX1 至 IPX6 相关条件"], ["适用对象", "外壳、零部件与整机"], ["配置", "喷淋方式与样品尺寸按项目确认"]], features: ["支持多类防水测试条件", "可用于汽车淋雨需求", "试验区域与喷淋配置可调整"] },
  sandDust: { family: "JH-1000 SERIES", name: "耐砂尘试验箱", image: "assets/products/catalog/sand-dust-chamber-dson.png", intro: "模拟粉尘环境，用于设备外壳、零部件与防护等级相关试验。", specs: [["系列", "JH-1000"], ["试验环境", "粉尘与砂尘模拟"], ["适用对象", "外壳、零部件与整机"], ["配置", "粉尘浓度与试验空间按项目确认"]], features: ["适合外壳防护与耐尘验证", "支持按样品尺寸配置", "试验条件以相关标准为准"] }
};

const detailRoot = document.querySelector("[data-product-detail]");
if (detailRoot) {
  const product = products[detailRoot.dataset.productKey];
  if (product) {
    detailRoot.innerHTML = `
      <section class="product-detail-hero"><div class="container product-detail-hero-grid"><div><p class="eyebrow">${product.family}</p><h1>${product.name}</h1><p>${product.intro}</p><div class="product-detail-actions"><a class="btn btn-primary" href="index.html#contact">咨询此产品</a><a class="btn btn-secondary" href="products.html">返回产品中心</a></div></div><div class="product-detail-image"><img src="${product.image}" alt="${product.name}" /></div></div></section>
      <section class="section product-detail-content"><div class="container"><div class="section-heading"><div><p class="section-label">CORE SPECIFICATIONS</p><h2>核心规格</h2></div></div><dl class="product-spec-list">${product.specs.map(([label, value]) => `<div><dt>${label}</dt><dd>${value}</dd></div>`).join("")}</dl><div class="product-detail-feature"><p class="section-label">APPLICATION & CONFIGURATION</p><h2>设备特点与配置方向</h2><ul>${product.features.map((feature) => `<li>${feature}</li>`).join("")}</ul><p class="product-detail-note">以上规格可依实际需求与配置调整，请以正式报价书及技术协议为准。</p></div></div></section>
      <section class="section section-accent"><div class="container contact-card-cta"><p class="section-label">PROJECT INQUIRY</p><h2>提供试验条件，确认适用配置</h2><p>请提供样品尺寸与重量、试验标准、温湿度范围、变化速率、供电、冷却方式与场地条件。</p><a class="btn btn-primary" href="index.html#contact">联系得声</a></div></section>`;
  }
}
